name: Bump version
on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read versionName property
        id: release_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: './app/version.properties'
          property: 'versionName'


      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_version.outputs.value }}
          release_name: Release ${{ steps.release_version.outputs.value }}
